### ISSUE TITLE
Apertura applicazione tramite tap sul widget

### ISSUE THREAD

**Issue by adnalb** [Xiryl/meteotrentino-app-deprecated#2]
Ciao,

potresti aggiungere la feature di apertura della applicazione al tap sul widget? lo fanno tutte le altre app meteo ed è molto comodo.

Complimenti per l'applicazione.

Adriano

**Comment by Xiryl** [comment]
ok, presa in carico, ETA 23/03/19

**Comment by Xiryl** [comment]
This app is deprecated. A new version is building.
Moving issue to new meteotrentino-app, ETA: Feb 2020
